import { test, expect } from '../../fixtures';
import { UserDataFactory } from '../../common/testData';

test.describe('User Registration', () => {
  test('Case 1: Register User with Generated Test Data', async ({ homePage, loginPage }) => {
    // Generate test data using factory - eliminates all hardcoded values
    const testUser = UserDataFactory.generateUser();

    // 1. Launch browser (handled by Playwright)
    // 2. Navigate to url 'http://automationexercise.com'
    await homePage.navigate();

    // Accept cookies if present (using our cookie handler)
    await homePage.acceptCookiesIfPresent();

    // 3. Verify that home page is visible successfully
    await expect(homePage.logo).toBeVisible();
    await expect(homePage.featuredItemsHeading).toBeVisible();

    // 4. Click on 'Signup / Login' button
    await homePage.navigateToSignupLogin();

    // 5. Verify 'New User Signup!' is visible
    await expect(loginPage.signupSection).toBeVisible();
    await expect(homePage.newUserSignupText).toBeVisible();

    // 6. Enter name and email address & 7. Click 'Signup' button
    await loginPage.startSignup(testUser.name, testUser.email);

    // 8. Verify that 'ENTER ACCOUNT INFORMATION' is visible
    await expect(loginPage.enterAccountInformationText).toBeVisible();

    // Wait for the signup form to be fully loaded
    await expect(loginPage.titleMrRadio).toBeVisible();

    // 9-12. Fill details: Title, Name, Email, Password, Date of birth, checkboxes, and personal info
    // 13. Fill signup form and create account (fillSignupForm includes clicking the create button)
    await loginPage.fillSignupForm(testUser);

    // 14. Verify that 'ACCOUNT CREATED!' is visible
    await expect(loginPage.accountCreatedText).toBeVisible();

    // 15. Click 'Continue' button
    await loginPage.continueButton.click();

    // 16. Verify that 'Logged in as username' is visible
    await expect(homePage.loggedInAsText(testUser.name)).toBeVisible();

    // 17. Click 'Delete Account' button
    await homePage.deleteAccountLink.click();

    // 18. Verify that 'ACCOUNT DELETED!' is visible and click 'Continue' button
    await expect(loginPage.accountDeletedText).toBeVisible();
    await loginPage.continueButton.click();

    // Verify we're back to home page after account deletion
    await expect(homePage.logo).toBeVisible();
  });

  test('Case 2: Register User with Custom Address', async ({ homePage, loginPage }) => {
    // Generate user with custom address - all faker-generated by default
    const testUser = UserDataFactory.generateUserWithCustomAddress();

    // Navigate and start signup
    await homePage.navigate();
    await homePage.acceptCookiesIfPresent();
    await expect(homePage.logo).toBeVisible();
    await homePage.navigateToSignupLogin();
    await expect(loginPage.signupSection).toBeVisible();

    // Start signup with generated user data
    await loginPage.startSignup(testUser.name, testUser.email);
    await expect(loginPage.enterAccountInformationText).toBeVisible();
    await expect(loginPage.titleMrRadio).toBeVisible();

    // Fill signup form
    await loginPage.fillSignupForm(testUser);
    await expect(loginPage.accountCreatedText).toBeVisible();

    // Cleanup
    await loginPage.continueButton.click();
    await expect(homePage.loggedInAsText(testUser.name)).toBeVisible();
    await homePage.deleteAccountLink.click();
    await expect(loginPage.accountDeletedText).toBeVisible();
  });
});
