export const LOCATORS = {
  COOKIE: {
    DIALOG: '.fc-dialog-container',
    CONSENT_BUTTON: 'button[name="Consent"]',
    MANAGE_OPTIONS_BUTTON: 'button[name="Manage options"]',
    LEARN_MORE_BUTTON: 'button[name="Learn more"]',
    PARTNERS_BUTTON: 'button[name="List of partners."]',
  },

  PRODUCT_LIST: {
    PRODUCT_CARDS: '.single-products',
    PRODUCT_NAMES: '.productinfo p',
    PRODUCT_PRICES: '.productinfo h2',
    ADD_TO_CART_BUTTONS: '.add-to-cart',
    VIEW_PRODUCT_LINKS: 'View Product',
  },

  ORDER_CONFIRMATION_MODAL: {
    CONTINUE_SHOPPING_BUTTON: 'Continue Shopping',
    VIEW_CART_BUTTON: 'View Cart',
  },

  HOME_PAGE: {
    LOGO: 'Website for automation practice',
    HOME_LINK: ' Home',
    PRODUCTS_LINK: ' Products',
    CART_LINK: ' Cart',
    SIGNUP_LOGIN_LINK: ' Signup / Login',
    TEST_CASES_LINK: ' Test Cases',
    API_TESTING_LINK: ' API Testing',
    VIDEO_TUTORIALS_LINK: ' Video Tutorials',
    CONTACT_US_LINK: ' Contact us',
    LOGOUT_LINK: ' Logout',
    DELETE_ACCOUNT_LINK: ' Delete Account',
    TEST_CASES_BUTTON: 'Test Cases',
    API_LIST_BUTTON: 'APIs list for practice',
    FEATURED_ITEMS_HEADING: 'Features Items',
    SUBSCRIPTION_HEADING: 'Subscription',
    EMAIL_INPUT: '#subscribe_email',
    SUBSCRIBE_BUTTON: '#subscribe',
  },

  LOGIN_PAGE: {
    LOGIN_SECTION: '.login-form',
    SIGNUP_SECTION: '.signup-form',
    SIGNUP_FORM_SECTION: '.signup-form form',
    LOGIN_EMAIL_INPUT: '[data-qa="login-email"]',
    LOGIN_PASSWORD_INPUT: '[data-qa="login-password"]',
    LOGIN_BUTTON: '[data-qa="login-button"]',
    SIGNUP_NAME_INPUT: '[data-qa="signup-name"]',
    SIGNUP_EMAIL_INPUT: '[data-qa="signup-email"]',
    SIGNUP_BUTTON: '[data-qa="signup-button"]',
    TITLE_MR_RADIO: '#id_gender1',
    TITLE_MRS_RADIO: '#id_gender2',
    PASSWORD_INPUT: '[data-qa="password"]',
    DAY_SELECT: '[data-qa="days"]',
    MONTH_SELECT: '[data-qa="months"]',
    YEAR_SELECT: '[data-qa="years"]',
    NEWSLETTER_CHECKBOX: '#newsletter',
    OFFERS_CHECKBOX: '#optin',
    FIRST_NAME_INPUT: '[data-qa="first_name"]',
    LAST_NAME_INPUT: '[data-qa="last_name"]',
    COMPANY_INPUT: '[data-qa="company"]',
    ADDRESS1_INPUT: '[data-qa="address"]',
    ADDRESS2_INPUT: '[data-qa="address2"]',
    COUNTRY_SELECT: '[data-qa="country"]',
    STATE_INPUT: '[data-qa="state"]',
    CITY_INPUT: '[data-qa="city"]',
    ZIPCODE_INPUT: '[data-qa="zipcode"]',
    MOBILE_NUMBER_INPUT: '[data-qa="mobile_number"]',
    CREATE_ACCOUNT_BUTTON: '[data-qa="create-account"]',
  },

  CART_PAGE: {
    CART_ITEMS: '#cart_info tbody tr',
    CART_PRODUCT_NAMES: '.cart_description a',
    CART_PRODUCT_PRICES: '.cart_price p',
    CART_PRODUCT_QUANTITIES: '.cart_quantity button',
    CART_PRODUCT_TOTALS: '.cart_total_price',
    REMOVE_BUTTONS: '.cart_quantity_delete',
    PROCEED_TO_CHECKOUT_BUTTON: '.check_out',
    REGISTER_LOGIN_LINK: 'Register / Login',
    EMPTY_CART: '#empty_cart',
  },

  PRODUCTS_PAGE: {
    SEARCH_INPUT: '#search_product',
    SEARCH_BUTTON: '#submit_search',
    PRODUCT_CARDS: '.features_items .single-products',
    CATEGORY_SIDEBAR: '.category-products',
    BRAND_SIDEBAR: '.brands_products',
  },

  PRODUCT_DETAILS_PAGE: {
    PRODUCT_IMAGE: '.product-details img[alt="ecommerce website products"]',
    PRODUCT_TITLE: '.product-details h2',
    PRODUCT_CATEGORY: '.product-details p:has-text("Category:")',
    PRODUCT_PRICE: '.product-information span span',
    PRODUCT_QUANTITY_INPUT: '#quantity',
    ADD_TO_CART_BUTTON: '.cart',
    PRODUCT_AVAILABILITY: '.product-details p:has-text("Availability:")',
    PRODUCT_CONDITION: '.product-details p:has-text("Condition:")',
    PRODUCT_BRAND: '.product-details p:has-text("Brand:")',
    REWIEW_SECTION: '.category-tab',
    REVIEW_NAME_INPUT: '#name',
    REVIEW_EMAIL_INPUT: '#email',
    REVIEW_TEXT_INPUT: '#review',
    REVIEW_SUBMIT_BUTTON: '#button-review',
  },
};
