import { faker } from '@faker-js/faker';
import { Address, AddressBuilder } from './AddressBuilder';

/**
 * User interface - complete user profile with all registration and personal information
 */
export interface User {
  name: string;
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  title: 'Mr' | 'Mrs';
  dateOfBirth: {
    day: string;
    month: string;
    year: string;
  };
  mobile: string;
  address: Address;
  newsletter: boolean;
  offers: boolean;
}

/**
 * User request data structure - flattened format with snake_case field names
 * Generated by UserDataFactory.toApiFormat() for API requests
 */
export interface UserRequestData {
  name: string;
  email: string;
  password: string;
  title: string;
  birth_date: string;
  birth_month: string;
  birth_year: string;
  firstname: string;
  lastname: string;
  company?: string;
  address1: string;
  address2?: string;
  country: string;
  zipcode: string;
  state: string;
  city: string;
  mobile_number: string;
}

/**
 * Test Data Factory - generates realistic test data using faker.js
 * Provides methods to create complete user profiles or customize specific fields
 */
export class UserDataFactory {
  /**
   * Generate a complete user with realistic faker data
   */
  static generateUser(overrides: Partial<User> = {}): User {
    const firstName = overrides.name?.split(' ')[0] || faker.person.firstName();
    const lastName = overrides.name?.split(' ')[1] || faker.person.lastName();
    const fullName = `${firstName} ${lastName}`;

    const address = new AddressBuilder({
      company: faker.company.name(),
      address1: faker.location.streetAddress(),
      country: 'United States',
      state: faker.location.state({ abbreviated: false }),
      city: faker.location.city(),
      zipcode: faker.location.zipCode(),
    });

    return {
      name: fullName,
      firstName,
      lastName,
      email: overrides.email || faker.internet.email({ provider: 'example.com' }),
      password: overrides.password || this.generatePassword(),
      title: overrides.title || 'Mr',
      dateOfBirth: overrides.dateOfBirth || this.generateDateOfBirth(),
      mobile: faker.phone.number({ style: 'international' }).replace(/\D/g, '').slice(-10),
      address: address.build(),
      newsletter: overrides.newsletter ?? true,
      offers: overrides.offers ?? true,
    };
  }

  /**
   * Generate user with custom address - uses faker for all address fields by default
   * @param addressOverrides Optional specific address field values to override
   * @param overrides Optional user data overrides
   */
  static generateUserWithCustomAddress(
    addressOverrides?: Partial<Address>,
    overrides: Partial<User> = {}
  ): User {
    const user = this.generateUser(overrides);
    const addressBuilder = new AddressBuilder(addressOverrides);
    user.address = addressBuilder.build();
    return user;
  }

  /**
   * Generate a strong password
   */
  private static generatePassword(): string {
    return `${faker.lorem.word()}${faker.number.int({ min: 100, max: 999 })}!`;
  }

  /**
   * Generate a realistic date of birth (age 18-65)
   * Returns numeric format for dropdown selection
   */
  private static generateDateOfBirth(): User['dateOfBirth'] {
    const birthDate = faker.date.birthdate({ min: 18, max: 65, mode: 'age' });

    return {
      day: String(birthDate.getDate()),
      month: String(birthDate.getMonth() + 1), // JavaScript months are 0-11, form expects 1-12
      year: String(birthDate.getFullYear()),
    };
  }

  /**
   * Generate multiple users
   */
  static generateUsers(count: number): User[] {
    return Array.from({ length: count }, () => this.generateUser());
  }

  /**
   * Generate user and convert to API format in one call
   * Returns the API-formatted user object with all fields needed for API tests
   */
  static generateApiTestUserData(overrides: Partial<User> = {}) {
    const user = this.generateUser(overrides);
    return this.toApiFormat(user);
  }

  /**
   * Generate invalid credentials for testing error scenarios
   */
  static generateInvalidCredentials() {
    return {
      nonexistentEmail: faker.internet.email({ provider: 'invalid-test.com' }),
      invalidPassword: `invalid${faker.number.int({ min: 100, max: 999 })}!`,
    };
  }

  /**
   * Convert User to API request format
   */
  static toApiFormat(user: User) {
    return {
      name: user.name,
      email: user.email,
      password: user.password,
      title: user.title,
      birth_date: user.dateOfBirth.day,
      birth_month: user.dateOfBirth.month,
      birth_year: user.dateOfBirth.year,
      firstname: user.firstName,
      lastname: user.lastName,
      company: user.address.company,
      address1: user.address.address1,
      address2: user.address.address2,
      country: user.address.country,
      zipcode: user.address.zipcode,
      state: user.address.state,
      city: user.address.city,
      mobile_number: user.mobile,
    };
  }
}
